---
- hosts: agents
  gather_facts: false
  tasks:
    - name: Install Hashi-up Consul Agents
      import_role:
        name: hashiup-consul-agents

    - name: Install Hashi-up Nomad Agents
      import_role:
        name: hashiup-nomad-agents